room-3
Valeru4/mimino-team-project pull request #16
Opened 2023-02-17 20:06 UTC by karanukvova

2023-02-17 20:46 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +        padding-top: 62px;
по макету падинг 66px

2023-02-17 20:47 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +            padding-bottom: 182px;
падинг 196px

2023-02-17 20:47 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +        margin-right: 91px;
попробуйте задать 110px и он тогда встанет по макету)

2023-02-17 20:50 UTC, SashaSasha707 requested changes
дождитесь еще коментариве Валерии)

2023-02-17 20:50 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +            padding-bottom: 182px;
падинг 196px

2023-02-17 20:50 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +        padding-top: 62px;
по макету падинг 66px

2023-02-17 20:50 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +        margin-right: 91px;
попробуйте задать 110px и он тогда встанет по макету)

2023-02-18 08:19 UTC, karanukvova commented on src/css/room-3-adult.css
> +        margin-right: 91px;
margin-bottom  чи margin-right?

2023-02-18 10:12 UTC, SashaSasha707 commented on src/css/room-3-adult.css
> +        margin-right: 91px;
margin-right
текст тогда выровняеться с заголовком

2023-02-18 19:21 UTC, SashaSasha707 approved these changes

2023-02-18 19:23 UTC, merged