Feature/amenities
Valeru4/mimino-team-project pull request #17
Opened 2023-02-17 21:05 UTC by LarisaBeskrovna

2023-02-17 22:45 UTC, SashaSasha707 requested changes
дождитесь еще комментариев Валерии)

2023-02-17 22:45 UTC, SashaSasha707 commented on src/css/amenities.css
> +@media (min-width: 1024px)
отображается как на мобильной версии

.amenities-button{
    padding: 18px 38px; - для таблетки и декстопа

2023-02-17 22:45 UTC, SashaSasha707 commented on src/css/amenities.css
> +.amenities-caption{
не хватает стрелочки назад

2023-02-18 13:39 UTC, LarisaBeskrovna commented on src/css/amenities.css
> +@media (min-width: 1024px)
ok

2023-02-18 13:52 UTC, LarisaBeskrovna commented on src/css/amenities.css
> +.amenities-caption{
ok

2023-02-19 11:46 UTC, SashaSasha707 approved these changes

2023-02-19 14:10 UTC, merged