Origin/feature/footer
Valeru4/mimino-team-project pull request #20
Opened 2023-02-18 08:18 UTC by Zhanna-Dm

Zhanna Dmytrenko

1. Footer html & css added.

2. Внесені зміни у файл ../img/sprite/icon.svg (іконки telegram, Facebook, instagram; назви Id не змінювала).

2023-02-18 12:50 UTC, SashaSasha707 requested changes
Не соответствуют отступы по макету между мимино, навигацией и социальными сетями в таблетке и декстопе. 

Если что пишите в тг

2023-02-18 12:50 UTC, SashaSasha707 commented on src/partials/footer.html
> +          <ul class="footer__social-icons">
иконки не в том порядке
инстагам, фейсбук и потом телеграмм

2023-02-18 12:50 UTC, SashaSasha707 commented on src/css/footer.css
> +@media screen and (min-width: 1024px) {
нижний паддинг 83px

2023-02-18 12:50 UTC, SashaSasha707 commented on src/css/footer.css
> +        margin-left: 137px;
там падинг больше 137. Плюсуется с отступом от меню navigation__items

2023-02-19 10:25 UTC, Zhanna-Dm commented on src/partials/footer.html
> +          <ul class="footer__social-icons">
Исправила.

2023-02-19 10:28 UTC, Zhanna-Dm commented on src/css/footer.css
> +        margin-left: 137px;
Переделывала футер, и вообще убрала этот марджин.  
<img width="475" alt="image" src="https://user-images.githubusercontent.com/115410891/219942424-825ea06f-bb04-4f6c-b9f4-89e2896c6ac3.png">

2023-02-19 12:14 UTC, SashaSasha707 approved these changes

2023-02-19 12:20 UTC, merged