Feature/details hotel main page
Valeru4/mimino-team-project pull request #31
Opened 2023-02-18 20:49 UTC by LarisaBeskrovna

2023-02-18 22:29 UTC, Valeru4 commented
Лариса, обновите, пожалуйста, мейн. И еще у меня на всех размерах єкрана стоит контейнер 414 и не меняется. Оформление контейнера можно не прописывать, он есть в бейс css. Также верхний паддинг мы задаем секции, а не диву с текстом. И нет стрелочек от слайдера (оформляем списком, кнопки и внутри свг)

2023-02-19 16:13 UTC, Oleksiy76 requested changes
Во всех <picture> у нас должно быть три <source> (min-width: 1280px, min-width: 1024px и max-width: 1023px) + <img>, которому желательно и height задать. Кроме того на каждом устройстве все фотографии разного размера, поэтому нужно выкачивать по 6 картинок каждой фотографии и вставлять в <picture> в соответствующий <source>

2023-02-19 16:13 UTC, Oleksiy76 commented on src/css/base.css
> +    --background-images:#DADADA;
тут либо прописать переменную, либо background-image вообше убрать, 
я убрал и оставил только тень, смотрю все так делали

2023-02-19 16:13 UTC, Oleksiy76 commented on src/css/hotel-main-page.css
> +font-family: 'Times New Roman';
во всех шрифтах через запятую надо добавить sans-serif

2023-02-19 16:13 UTC, Oleksiy76 commented on src/css/hotel-main-page.css
> +    @media screen and (max-width:1024px)
медиа-запросы у нас прописаны через min-width и после двоеточия идёт пробел

2023-02-19 16:13 UTC, Oleksiy76 commented on src/partials/hotel-main-page.html
> +                  <use href="../img/sprite/icon.svg#icon-Vector-1">
тут одна точка "в пути" лишняя

2023-02-19 16:13 UTC, Oleksiy76 commented on src/partials/hotel-main-page.html
> +                  <use href="../img/sprite/icon.svg#icon-Vector-2">
и тут

2023-02-19 17:01 UTC, LarisaBeskrovna commented on src/css/base.css
> +    --background-images:#DADADA;
ок

2023-02-19 17:02 UTC, LarisaBeskrovna commented on src/css/hotel-main-page.css
> +font-family: 'Times New Roman';
ок

2023-02-19 17:04 UTC, LarisaBeskrovna commented on src/css/hotel-main-page.css
> +    @media screen and (max-width:1024px)
ок

2023-02-19 17:05 UTC, LarisaBeskrovna commented on src/partials/hotel-main-page.html
> +                  <use href="../img/sprite/icon.svg#icon-Vector-1">
ок

2023-02-19 17:06 UTC, LarisaBeskrovna commented on src/partials/hotel-main-page.html
> +                  <use href="../img/sprite/icon.svg#icon-Vector-2">
ок

2023-02-19 23:29 UTC, Oleksiy76 approved these changes

2023-02-19 23:48 UTC, merged